[0m11:32:47.376849 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020B21FC8350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020B246CA850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020B246B7310>]}


============================== 11:32:47.379851 | 5bd8f629-a6d3-43a5-b0ef-382fee9af06e ==============================
[0m11:32:47.379851 [info ] [MainThread]: Running with dbt=1.5.3
[0m11:32:47.379851 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\tecna\\.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m11:32:47.381853 [debug] [MainThread]: Starter project path: C:\Users\tecna\anaconda3\Lib\site-packages\dbt\include\starter_project
[0m11:32:51.680238 [info ] [MainThread]: 
Your new dbt project "desafio" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m11:32:51.680815 [debug] [MainThread]: Command `dbt init` succeeded at 11:32:51.680815 after 4.32 seconds
[0m11:32:51.680815 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020B24338A50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020B1E05BE10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020B1E0EA290>]}
[0m11:32:51.681886 [debug] [MainThread]: Flushing usage events
[0m11:32:58.246623 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002BCE728EB50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002BCE728E990>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002BCE72786D0>]}


============================== 11:32:58.248566 | dc67c813-6aa9-4eb4-8c60-3b5af8b53885 ==============================
[0m11:32:58.248566 [info ] [MainThread]: Running with dbt=1.5.3
[0m11:32:58.249559 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\tecna\\.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m11:32:58.250620 [info ] [MainThread]: dbt version: 1.5.3
[0m11:32:58.250620 [info ] [MainThread]: python version: 3.11.4
[0m11:32:58.251615 [info ] [MainThread]: python path: C:\Users\tecna\anaconda3\python.exe
[0m11:32:58.251615 [info ] [MainThread]: os info: Windows-10-10.0.22621-SP0
[0m11:32:58.251615 [info ] [MainThread]: Using profiles.yml file at C:\Users\tecna\.dbt\profiles.yml
[0m11:32:58.252569 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\tecna\emd-desafio-data-eng\desafio\dbt_project.yml
[0m11:32:58.252569 [info ] [MainThread]: Configuration:
[0m11:32:58.287555 [info ] [MainThread]:   profiles.yml file [[31mERROR invalid[0m]
[0m11:32:58.288554 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m11:32:58.288554 [info ] [MainThread]: Required dependencies:
[0m11:32:58.288554 [debug] [MainThread]: Executing "git --help"
[0m11:32:58.322554 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--config-env=<name>=<envvar>] <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m11:32:58.323565 [debug] [MainThread]: STDERR: "b''"
[0m11:32:58.323565 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m11:32:58.324554 [info ] [MainThread]: [31m2 checks failed:[0m
[0m11:32:58.324554 [info ] [MainThread]: Could not load dbt_project.yml

[0m11:32:58.325561 [info ] [MainThread]: Profile loading failed for the following reason:
Runtime Error
  Credentials in profile "dbt_desafio", target "dev" invalid: ['dbname'] is not of type 'string'

Runtime Error
  Credentials in profile "desafio", target "dev" invalid: ['dbname'] is not of type 'string'


[0m11:32:58.325561 [debug] [MainThread]: Command `dbt debug` failed at 11:32:58.325561 after 0.10 seconds
[0m11:32:58.326564 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002BCE72785D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002BCE0D0BDD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002BCE0D0BE10>]}
[0m11:32:58.326564 [debug] [MainThread]: Flushing usage events
[0m14:05:01.846140 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021B13D08550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021B13988F90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021B13D08110>]}


============================== 14:05:01.850149 | 408878c4-39d2-4fb8-8c46-fecdcee51a6a ==============================
[0m14:05:01.850149 [info ] [MainThread]: Running with dbt=1.5.3
[0m14:05:01.851140 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\tecna\\emd-desafio-data-eng\\desafio', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m14:05:01.851140 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\tecna\emd-desafio-data-eng\desafio\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:05:01.852141 [debug] [MainThread]: Command `dbt run` failed at 14:05:01.852141 after 0.02 seconds
[0m14:05:01.852141 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021B13D17BD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021B13D02710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021B13D03110>]}
[0m14:05:01.853141 [debug] [MainThread]: Flushing usage events
[0m14:06:13.331389 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000113C7AF8650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000113C7AF3550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000113C7AF31D0>]}


============================== 14:06:13.334398 | 87c52413-cee9-4f4b-9423-3b1df5d195fb ==============================
[0m14:06:13.334398 [info ] [MainThread]: Running with dbt=1.5.3
[0m14:06:13.335389 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\tecna\\emd-desafio-data-eng\\desafio', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m14:06:13.335389 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\tecna\emd-desafio-data-eng\desafio\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:06:13.336390 [debug] [MainThread]: Command `dbt run` failed at 14:06:13.336390 after 0.02 seconds
[0m14:06:13.336390 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000113C7B07B10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000113C7AF2690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000113C7AF3550>]}
[0m14:06:13.337390 [debug] [MainThread]: Flushing usage events
[0m14:07:45.345257 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023969618650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023969618310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002396961A190>]}


============================== 14:07:45.350267 | f5bb6a7a-47a3-4bdd-be0b-499a01447a36 ==============================
[0m14:07:45.350267 [info ] [MainThread]: Running with dbt=1.5.3
[0m14:07:45.351257 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\tecna\\emd-desafio-data-eng\\desafio', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m14:07:45.351257 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\tecna\emd-desafio-data-eng\desafio\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:07:45.352258 [debug] [MainThread]: Command `dbt run` failed at 14:07:45.352258 after 0.02 seconds
[0m14:07:45.352258 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023969623D50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002396930F150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002396905F710>]}
[0m14:07:45.353258 [debug] [MainThread]: Flushing usage events
[0m14:08:49.468963 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F7C95E7E10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F7C95E8190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F7C95E9D50>]}


============================== 14:08:49.470965 | 7811d349-30c7-4719-9d9e-d1165a5da5d3 ==============================
[0m14:08:49.470965 [info ] [MainThread]: Running with dbt=1.5.3
[0m14:08:49.471963 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\tecna\\emd-desafio-data-eng\\desafio', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m14:08:49.472963 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\tecna\emd-desafio-data-eng\desafio\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:08:49.472963 [debug] [MainThread]: Command `dbt run` failed at 14:08:49.472963 after 0.02 seconds
[0m14:08:49.473962 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F7C91C6D50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F7C95E65D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F7C95E5F50>]}
[0m14:08:49.473962 [debug] [MainThread]: Flushing usage events
[0m14:09:52.949285 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016382C7EB50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016382F98210>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016382F98090>]}


============================== 14:09:52.952239 | 7c992bb7-82c9-4e98-9ef5-3cc03209cb8d ==============================
[0m14:09:52.952239 [info ] [MainThread]: Running with dbt=1.5.3
[0m14:09:52.953238 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\tecna\\emd-desafio-data-eng\\desafio', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m14:09:52.953238 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\tecna\emd-desafio-data-eng\desafio\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:09:52.954238 [debug] [MainThread]: Command `dbt run` failed at 14:09:52.954238 after 0.02 seconds
[0m14:09:52.954238 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016382FA3990>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016382F964D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016382F95F50>]}
[0m14:09:52.955239 [debug] [MainThread]: Flushing usage events
[0m14:10:56.254555 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020E432B84D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020E42EA7A10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020E432B9890>]}


============================== 14:10:56.257546 | 7335daa9-5777-41ca-a093-5f0985310018 ==============================
[0m14:10:56.257546 [info ] [MainThread]: Running with dbt=1.5.3
[0m14:10:56.257546 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\tecna\\emd-desafio-data-eng\\desafio', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m14:10:56.259051 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\tecna\emd-desafio-data-eng\desafio\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:10:56.259051 [debug] [MainThread]: Command `dbt run` failed at 14:10:56.259051 after 0.02 seconds
[0m14:10:56.260074 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020E42FAEAD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020E42FAEE10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020E432B7E10>]}
[0m14:10:56.261057 [debug] [MainThread]: Flushing usage events
[0m14:12:00.044499 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C1747D8290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C174450F90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C1747D31D0>]}


============================== 14:12:00.047497 | 935613c1-4e6b-41ca-8c8e-aebaa5427fa7 ==============================
[0m14:12:00.047497 [info ] [MainThread]: Running with dbt=1.5.3
[0m14:12:00.047497 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\tecna\\emd-desafio-data-eng\\desafio', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m14:12:00.049010 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\tecna\emd-desafio-data-eng\desafio\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:12:00.049010 [debug] [MainThread]: Command `dbt run` failed at 14:12:00.049010 after 0.02 seconds
[0m14:12:00.050031 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C1747E7B10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C1747E78D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C1724E4450>]}
[0m14:12:00.050031 [debug] [MainThread]: Flushing usage events
[0m14:13:03.916612 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A167FD8790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A167FD2010>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A167FD8110>]}


============================== 14:13:03.920140 | f573a908-1ab0-4347-a8cc-5c5c9401003a ==============================
[0m14:13:03.920140 [info ] [MainThread]: Running with dbt=1.5.3
[0m14:13:03.921151 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\tecna\\emd-desafio-data-eng\\desafio', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m14:13:03.922132 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\tecna\emd-desafio-data-eng\desafio\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:13:03.923131 [debug] [MainThread]: Command `dbt run` failed at 14:13:03.923131 after 0.02 seconds
[0m14:13:03.923131 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A167FE7A50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A167CBEF90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A167FD2650>]}
[0m14:13:03.923131 [debug] [MainThread]: Flushing usage events
[0m14:14:07.633595 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ED2A4183D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ED2A099250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ED2A4131D0>]}


============================== 14:14:07.636598 | 40387c61-9b45-48fa-8d22-2b9d24350f06 ==============================
[0m14:14:07.636598 [info ] [MainThread]: Running with dbt=1.5.3
[0m14:14:07.637587 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\tecna\\emd-desafio-data-eng\\desafio', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m14:14:07.638597 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\tecna\emd-desafio-data-eng\desafio\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:14:07.638597 [debug] [MainThread]: Command `dbt run` failed at 14:14:07.638597 after 0.02 seconds
[0m14:14:07.639587 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ED2A427B50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ED2A10EE10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ED2A412690>]}
[0m14:14:07.639587 [debug] [MainThread]: Flushing usage events
[0m14:15:11.052628 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001756235C590>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017562AA8410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017562AA9ED0>]}


============================== 14:15:11.057628 | 4e7a0b0e-d854-46ae-803a-ab0f41ee614d ==============================
[0m14:15:11.057628 [info ] [MainThread]: Running with dbt=1.5.3
[0m14:15:11.057628 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\tecna\\emd-desafio-data-eng\\desafio', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m14:15:11.059134 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\tecna\emd-desafio-data-eng\desafio\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:15:11.060139 [debug] [MainThread]: Command `dbt run` failed at 14:15:11.060139 after 0.02 seconds
[0m14:15:11.061143 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017562AB3BD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017562AAA790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017562AA9ED0>]}
[0m14:15:11.061143 [debug] [MainThread]: Flushing usage events
[0m14:16:14.362645 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021B48968390>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021B48969910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021B48969E50>]}


============================== 14:16:14.365653 | 9578a884-9375-44a6-a867-26f412bb709b ==============================
[0m14:16:14.365653 [info ] [MainThread]: Running with dbt=1.5.3
[0m14:16:14.366655 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\tecna\\emd-desafio-data-eng\\desafio', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m14:16:14.367653 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\tecna\emd-desafio-data-eng\desafio\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:16:14.367653 [debug] [MainThread]: Command `dbt run` failed at 14:16:14.367653 after 0.02 seconds
[0m14:16:14.368645 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021B48966590>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021B48966110>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021B48965CD0>]}
[0m14:16:14.368645 [debug] [MainThread]: Flushing usage events
[0m14:17:17.486663 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B576938490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B5765B8F90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B576938250>]}


============================== 14:17:17.489668 | 2e895f06-3bd4-4f09-9041-8968ba0f9cb1 ==============================
[0m14:17:17.489668 [info ] [MainThread]: Running with dbt=1.5.3
[0m14:17:17.490678 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\tecna\\emd-desafio-data-eng\\desafio', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m14:17:17.491681 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\tecna\emd-desafio-data-eng\desafio\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:17:17.492189 [debug] [MainThread]: Command `dbt run` failed at 14:17:17.492189 after 0.02 seconds
[0m14:17:17.492189 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B576943B50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B57662EE10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B576932610>]}
[0m14:17:17.492189 [debug] [MainThread]: Flushing usage events
[0m14:18:20.851984 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023E00428490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023E00428410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023E00429F10>]}


============================== 14:18:20.854993 | 4643ebc0-32b8-47b9-9042-374c566350f3 ==============================
[0m14:18:20.854993 [info ] [MainThread]: Running with dbt=1.5.3
[0m14:18:20.855985 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\tecna\\emd-desafio-data-eng\\desafio', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m14:18:20.855985 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\tecna\emd-desafio-data-eng\desafio\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:18:20.856985 [debug] [MainThread]: Command `dbt run` failed at 14:18:20.856985 after 0.02 seconds
[0m14:18:20.856985 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023E00433E10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023E00422850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023E00423110>]}
[0m14:18:20.856985 [debug] [MainThread]: Flushing usage events
